export const SITE_BUILD = '2026-09-17-restore-step1'

export const chapters = [
  {id:'start', n:'01', title:'Разрешение начать', free:true, taskCount:6, mood:'начать без идеального плана', note:'Войти в сезон мягко: найти дневник, заметить первую осень и оставить живой след.', image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=82'},
  {id:'signs', n:'02', title:'Первые признаки', free:false, taskCount:6, mood:'заметить перемену', note:'Поймать первые детали, по которым становится ясно: сезон уже сменился.', image:'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1200&q=82'},
  {id:'body', n:'03', title:'Тело входит в осень', free:false, taskCount:6, mood:'почувствовать сезон телом', note:'Сон, свет, прогулки, еда и темп — осень начинается не только за окном.', image:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&q=82'},
  {id:'book', n:'04', title:'Книга моей осени', free:false, taskCount:6, mood:'читать медленнее', note:'Собрать личную книжную полку сезона и сохранить одну важную страницу.', image:'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=1200&q=82'},
  {id:'taste', n:'05', title:'Вкус осени', free:false, taskCount:6, mood:'запомнить через вкус', note:'Домашняя еда, тёплые ритуалы и рецепты, которые хочется переписать от руки.', image:'https://images.unsplash.com/photo-1478145046317-39f10e56b5e9?auto=format&fit=crop&w=1200&q=82'},
  {id:'city', n:'06', title:'Город меняется', free:false, taskCount:6, mood:'увидеть знакомое заново', note:'Пройти привычный город как временную выставку — медленнее и внимательнее.', image:'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=82'},
  {id:'people', n:'07', title:'Люди моей осени', free:false, taskCount:6, mood:'сохранить присутствие', note:'Не список встреч, а люди, фразы и маленькие моменты, которые хочется оставить.', image:'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=82'},
  {id:'offline', n:'08', title:'День без доказательств', free:false, taskCount:6, mood:'ничего не публиковать', note:'Прожить красивый кусок дня, который не обязан становиться контентом.', image:'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=82'},
  {id:'memory', n:'09', title:'Осень из прошлого', free:false, taskCount:6, mood:'услышать память', note:'Вернуться к старым фотографиям, музыке и одной осени, которая всё ещё живёт внутри.', image:'https://images.unsplash.com/photo-1508704019882-f9cf40e475b4?auto=format&fit=crop&w=1200&q=82'},
  {id:'rain', n:'10', title:'Плохая погода', free:false, taskCount:6, mood:'не ждать идеального дня', note:'Научиться замечать жизнь и в сером свете, ветре, дожде и ранних сумерках.', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=82'},
  {id:'collect', n:'11', title:'Собрать осень', free:false, taskCount:6, mood:'собрать архив', note:'Из фотографий, записок, билетов и листьев сложить собственную коллекцию сезона.', image:'https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?auto=format&fit=crop&w=1200&q=82'},
  {id:'leaf', n:'12', title:'Последний лист', free:false, taskCount:6, mood:'закрыть сезон', note:'Посмотреть назад и увидеть не процент выполнения, а свою прожитую осень.', image:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=82'}
]

export const freeTasks = [
  {id:'read', verb:'ПРОЧИТАТЬ', title:'Прочитать Тютчева вслух', note:'Открой стихотворение «Есть в осени первоначальной…». Прочитай вслух медленно, без анализа. Отметь 2–4 строки, которые сегодня звучат как твои.', prompt:'Перепиши выбранные строки в бумажный дневник и рядом допиши: «Я заметила в них…».', image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=82', archiveTitle:'Строки, которые захотелось забрать с собой'},
  {id:'look', verb:'ПОСМОТРЕТЬ', title:'Три минуты смотреть Левитана', note:'Не листай подборку. Выбери одну работу Левитана и три минуты рассматривай только её: свет, воздух, дорогу, расстояние, тишину.', prompt:'Запиши одну деталь картины, которую раньше бы пропустила.', image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=82', archiveTitle:'Деталь, которую я раньше бы пропустила'},
  {id:'walk', verb:'ВЫЙТИ', title:'Пройти одну остановку пешком', note:'Не устраивай большую прогулку. Выйди на одну остановку раньше или пройди короткий знакомый отрезок пешком.', prompt:'Найди один признак осени, который невозможно было бы заметить из транспорта.', image:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=82', archiveTitle:'Мой маленький осенний маршрут'},
  {id:'listen', verb:'ПОСЛУШАТЬ', title:'Послушать осень без наушников', note:'Пять минут без музыки и подкаста. Услышь свой двор, улицу, парк или открытое окно.', prompt:'Запиши три звука. Даже самые обычные.', image:'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1200&q=82', archiveTitle:'Три звука этого дня'},
  {id:'write', verb:'ЗАПИСАТЬ', title:'Три строки о сегодняшнем дне', note:'Без красивого текста. Три конкретные строки: что увидела, что почувствовала, что хочется удержать.', prompt:'Начни с «Сегодня было…» и не редактируй.', image:'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1200&q=82', archiveTitle:'Короткая запись без редакции'},
  {id:'keep', verb:'СОХРАНИТЬ', title:'Сохранить один живой след', note:'Билет, лист, чек, маленькая фотография, этикетка, записка — что-то физическое из сегодняшнего дня.', prompt:'Приклей или положи его в дневник. Подпиши дату и одну фразу.', image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=82', archiveTitle:'След, который остался со мной'}
]

export const bonuses = [
  {n:'01', title:'Пять осенних рецептов', tag:'доступно бесплатно', text:'Рецепты как страницы домашней тетради — с фотографиями, продуктами и короткими шагами.', free:true, image:'https://images.unsplash.com/photo-1478145046317-39f10e56b5e9?auto=format&fit=crop&w=1200&q=82'},
  {n:'02', title:'Плейлисты для трёх месяцев', tag:'в полном сезоне', text:'Сентябрь — открывать. Октябрь — проживать. Ноябрь — сохранять.', image:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=82'},
  {n:'03', title:'Книги, фильмы и подкасты', tag:'в полном сезоне', text:'Небольшие подборки к главам: только то, что действительно продолжает тему, а не заполняет время.', image:'https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=1200&q=82'},
  {n:'04', title:'Навигатор «Город рядом»', tag:'в полном сезоне', text:'Маршруты-наблюдения, которые работают в любом городе: двор, рынок, библиотека, набережная или парк.', image:'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=82'}
]
